In [4]:
import numpy as np
a = np.array([1, 7, 20, 10, 4, 11, 25])
print([a>10])
print(a[a>10])


[array([False, False,  True, False, False,  True,  True])]
[20 11 25]


In [6]:
x = np.array([[3,2,5],[1,6,7]])
x

array([[3, 2, 5],
       [1, 6, 7]])

In [7]:
x[0][0]


3

In [8]:
np.array([1,2,3,4,5]) * 2


array([ 2,  4,  6,  8, 10])

In [9]:
[1,2,3,4,5] * 2


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [12]:
#load the dataset
import statsmodels.api as sm
demog_dataset = sm.datasets.get_rdataset(dataname = "Leinhardt",package = "carData")
demog = demog_dataset.data
#retrieve information about the dataset
# print(demog_dataset.__doc__)
null_columns = demog.columns[demog.isnull().any()]
print(null_columns)



Index(['infant'], dtype='object')


In [13]:
mean_income = demog['income'].mean()
rounded_mean_income = round(mean_income, 2)

print(rounded_mean_income)


998.07


In [14]:
oil_countries_count = len(demog[demog['oil'] == 'yes'])
print(oil_countries_count)


9


In [32]:
contains_taiwan = 'Taiwan' in demog.index
contains_taiwan

True